name: SphereWorld
main: com.bukkit.toasterktn.SphereWorld.SphereWorld
version: 0.5
commands: 
   regeneratechunk:
      description: Regen a Chunk
      usage: /<command> [x] [z]
      aliases: 
         - regc
         - cr
   sphere:
      description: Shows information about the Sphere you are in
      usage: /<command>